### ISSUE TITLE
Unity 2021以降でdebugがoffなので動作がなんか違う

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/ConsoleLogSaver#15]

**Comment by anatawa12** [comment]
Debug onにしろと書くか

**Comment by Sayamame-beans** [comment]
画像か何かで、ここでDebugをOnにしてくださいみたいな案内があると親切かも
(VRCSDKが2022対応したのでコメント)

**Comment by anatawa12** [comment]
https://note.com/azukimochi25/n/n042c495e55f4?sub_rt=share_pb の方からスクショ拝借していいかも

**Comment by anatawa12** [comment]
READMEにステップ追加したけどこれでいいかな

**Comment by Sayamame-beans** [comment]
2022表記で良いのです? (2021以降?)

**Comment by anatawa12** [comment]
あー2021もそうなんだっけ。要修正

**Comment by Sayamame-beans** [comment]
(ここのissueタイトルが2021だったのと、planeta絡みの時は2021だった気がしたので)

**Comment by anatawa12** [comment]
修正した。
