### ISSUE TITLE
[FeatReq] [Viewer] パッケージ一覧やUnityバージョンなどの情報も一緒に表示して欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/ConsoleLogSaver#22]
ファイルを直接読むとUPM/VPM dependenciesやUnityバージョン、ビルドターゲットなどの情報を確認することが出来ますが、Viewer上で一緒に見れると嬉しいと思います。

**Comment by anatawa12** [comment]
どこに表示するか問題を解決できてなくてやってない感じなので案ぼしゅう

**Comment by Sayamame-beans** [comment]
それ用のタブを生やす感じが分かりやすくはありそう…?
代わりに、ログ表示の一番上に(仮想的にログの1つとして)入れるのも案としてはありそうです。
